version: "3.8"

services:
  backend:
    build: ./server
    expose:
      - "5000"
    env_file:
      - ./server/.env
    restart: always
  frontend:
    build: ./clients
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
